-- =============================================================================
-- create_VALIDATED_TRAUMA_SCORES.sql
-- =============================================================================
-- Purpose:      Create validated.trauma_scores table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      30 (5 governance + 25 domain)
-- Sources:      CISIR, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.trauma_scores (
    -- Governance columns
    validated_id               SERIAL PRIMARY KEY,
    source_type                TEXT NOT NULL,
    source_table               TEXT NOT NULL,
    ingest_id                  TEXT NOT NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number             TEXT,
    ais_abdomen_max            INTEGER,
    ais_body_region_max_detail TEXT,
    ais_brain_max              INTEGER,
    ais_face_max               INTEGER,
    ais_head_max               INTEGER,
    ais_lower_extremity_max    INTEGER,
    ais_max_overall            INTEGER,
    ais_neck_max               INTEGER,
    ais_other_max              INTEGER,
    ais_spine_max              INTEGER,
    ais_thorax_max             INTEGER,
    ais_upper_extremity_max    INTEGER,
    cisir_id                   TEXT,
    gcs_total_admission        INTEGER,
    iss                        INTEGER,
    iss_ais1990                INTEGER,
    iss_ais2005                INTEGER,
    mrn                        TEXT,
    rts_admission              NUMERIC,
    rts_scene                  NUMERIC,
    trauma_number              TEXT,
    triss                      NUMERIC,
    triss_ais1990              INTEGER,
    triss_ais2005              NUMERIC

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_trauma_scores_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_trauma_scores_source_type
    ON validated.trauma_scores (source_type);

CREATE INDEX IF NOT EXISTS idx_trauma_scores_ingest_id
    ON validated.trauma_scores (ingest_id);

CREATE INDEX IF NOT EXISTS idx_trauma_scores_account_number
    ON validated.trauma_scores (account_number);

CREATE INDEX IF NOT EXISTS idx_trauma_scores_mrn
    ON validated.trauma_scores (mrn);

CREATE INDEX IF NOT EXISTS idx_trauma_scores_trauma_number
    ON validated.trauma_scores (trauma_number);

CREATE INDEX IF NOT EXISTS idx_trauma_scores_cisir_id
    ON validated.trauma_scores (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.trauma_scores IS
'Harmonized trauma scores data combined from: CISIR, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.trauma_scores.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.trauma_scores.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.trauma_scores.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.trauma_scores.created_at IS
'Timestamp when this row was inserted into the validated table.';

