-- =============================================================================
-- create_VALIDATED_MICRO_SENSITIVITIES.sql
-- =============================================================================
-- Purpose:      Create validated.micro_sensitivities table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      20 (5 governance + 15 domain)
-- Sources:      CLARITY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.micro_sensitivities (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    antibiotic_code         TEXT,
    drug_name               TEXT,
    encounter_csn           TEXT,
    order_procedure_id      TEXT,
    order_value             TEXT,
    organism                TEXT,
    organism_id             TEXT,
    pat_id                  TEXT,
    result_datetime         DATE,
    result_line             INTEGER,
    sensitivity_line        INTEGER,
    sensitivity_value       TEXT,
    susceptibility          TEXT,
    susceptibility_code     TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_micro_sensitivities_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_micro_sensitivities_source_type
    ON validated.micro_sensitivities (source_type);

CREATE INDEX IF NOT EXISTS idx_micro_sensitivities_ingest_id
    ON validated.micro_sensitivities (ingest_id);

CREATE INDEX IF NOT EXISTS idx_micro_sensitivities_account_number
    ON validated.micro_sensitivities (account_number);

CREATE INDEX IF NOT EXISTS idx_micro_sensitivities_encounter_csn
    ON validated.micro_sensitivities (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_micro_sensitivities_pat_id
    ON validated.micro_sensitivities (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.micro_sensitivities IS
'Harmonized micro sensitivities data combined from: CLARITY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.micro_sensitivities.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.micro_sensitivities.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.micro_sensitivities.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.micro_sensitivities.created_at IS
'Timestamp when this row was inserted into the validated table.';

