-- =============================================================================
-- create_VALIDATED_PMH.sql
-- =============================================================================
-- Purpose:      Create validated.pmh table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      18 (5 governance + 13 domain)
-- Sources:      CISIR, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.pmh (
    -- Governance columns
    validated_id                  SERIAL PRIMARY KEY,
    source_type                   TEXT NOT NULL,
    source_table                  TEXT NOT NULL,
    ingest_id                     TEXT NOT NULL,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number                TEXT,
    admission_date                TIMESTAMP,
    age                           INTEGER,
    cisir_id                      TEXT,
    hospital_arrival_datetime     TIMESTAMP,
    icd10_code                    TEXT,
    icd9_code                     TEXT,
    icd9_preexisting_condition_id TEXT,
    last_name                     TEXT,
    mrn                           TEXT,
    pmh_category                  TEXT,
    pmh_description               TEXT,
    trauma_number                 TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_pmh_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_pmh_source_type
    ON validated.pmh (source_type);

CREATE INDEX IF NOT EXISTS idx_pmh_ingest_id
    ON validated.pmh (ingest_id);

CREATE INDEX IF NOT EXISTS idx_pmh_account_number
    ON validated.pmh (account_number);

CREATE INDEX IF NOT EXISTS idx_pmh_mrn
    ON validated.pmh (mrn);

CREATE INDEX IF NOT EXISTS idx_pmh_trauma_number
    ON validated.pmh (trauma_number);

CREATE INDEX IF NOT EXISTS idx_pmh_cisir_id
    ON validated.pmh (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.pmh IS
'Harmonized pmh data combined from: CISIR, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.pmh.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.pmh.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.pmh.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.pmh.created_at IS
'Timestamp when this row was inserted into the validated table.';

