-- =============================================================================
-- create_VALIDATED_DISCHARGE.sql
-- =============================================================================
-- Purpose:      Create validated.discharge table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      26 (5 governance + 21 domain)
-- Sources:      CISIR, CLARITY, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.discharge (
    -- Governance columns
    validated_id                SERIAL PRIMARY KEY,
    source_type                 TEXT NOT NULL,
    source_table                TEXT NOT NULL,
    ingest_id                   TEXT NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number              TEXT,
    autopsy_number              TEXT,
    brain_death_datetime        TIMESTAMP,
    cisir_id                    TEXT,
    discharge_date              DATE,
    discharge_datetime          TIMESTAMP,
    discharge_destination       TEXT,
    discharge_disposition       TEXT,
    discharge_disposition_id    TEXT,
    discharge_time              TIME,
    discharge_unit              TEXT,
    discharge_unit_id           TEXT,
    encounter_csn               TEXT,
    length_of_stay              NUMERIC,
    medical_examiner_number     TEXT,
    mrn                         TEXT,
    pat_id                      TEXT,
    total_icu_days              NUMERIC,
    trauma_number               TEXT,
    ventilator_days             INTEGER,
    withdrawal_of_care_datetime TIMESTAMP

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_discharge_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_discharge_source_type
    ON validated.discharge (source_type);

CREATE INDEX IF NOT EXISTS idx_discharge_ingest_id
    ON validated.discharge (ingest_id);

CREATE INDEX IF NOT EXISTS idx_discharge_account_number
    ON validated.discharge (account_number);

CREATE INDEX IF NOT EXISTS idx_discharge_mrn
    ON validated.discharge (mrn);

CREATE INDEX IF NOT EXISTS idx_discharge_trauma_number
    ON validated.discharge (trauma_number);

CREATE INDEX IF NOT EXISTS idx_discharge_cisir_id
    ON validated.discharge (cisir_id);

CREATE INDEX IF NOT EXISTS idx_discharge_encounter_csn
    ON validated.discharge (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_discharge_pat_id
    ON validated.discharge (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.discharge IS
'Harmonized discharge data combined from: CISIR, CLARITY, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.discharge.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.discharge.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.discharge.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.discharge.created_at IS
'Timestamp when this row was inserted into the validated table.';

