-- =============================================================================
-- create_VALIDATED_LABS.sql
-- =============================================================================
-- Purpose:      Create validated.labs table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      37 (5 governance + 32 domain)
-- Sources:      CISIR, CLARITY, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.labs (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    admit_to_order_minutes  INTEGER,
    admit_to_result_minutes NUMERIC,
    cerner_order_number     TEXT,
    cisir_id                TEXT,
    component_id            TEXT,
    component_name          TEXT,
    encounter_csn           TEXT,
    lab_group               TEXT,
    lab_test                TEXT,
    loinc_code              TEXT,
    loinc_component         TEXT,
    mrn                     TEXT,
    normal_range            TEXT,
    observation_code_system TEXT,
    observation_datetime    TIMESTAMP,
    order_datetime          TIMESTAMP,
    order_id                TEXT,
    order_name              TEXT,
    order_to_result_minutes INTEGER,
    pat_id                  TEXT,
    provider_id             TEXT,
    result_datetime         TIMESTAMP,
    result_numeric_value    NUMERIC,
    result_text_value       TEXT,
    result_type             TEXT,
    result_units            TEXT,
    result_value            NUMERIC,
    specimen_taken_datetime TIMESTAMP,
    test_id                 TEXT,
    test_name               TEXT,
    trauma_number           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_labs_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_labs_source_type
    ON validated.labs (source_type);

CREATE INDEX IF NOT EXISTS idx_labs_ingest_id
    ON validated.labs (ingest_id);

CREATE INDEX IF NOT EXISTS idx_labs_account_number
    ON validated.labs (account_number);

CREATE INDEX IF NOT EXISTS idx_labs_mrn
    ON validated.labs (mrn);

CREATE INDEX IF NOT EXISTS idx_labs_trauma_number
    ON validated.labs (trauma_number);

CREATE INDEX IF NOT EXISTS idx_labs_cisir_id
    ON validated.labs (cisir_id);

CREATE INDEX IF NOT EXISTS idx_labs_encounter_csn
    ON validated.labs (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_labs_pat_id
    ON validated.labs (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.labs IS
'Harmonized labs data combined from: CISIR, CLARITY, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.labs.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.labs.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.labs.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.labs.created_at IS
'Timestamp when this row was inserted into the validated table.';

