-- =============================================================================
-- create_VALIDATED_PROCEDURES.sql
-- =============================================================================
-- Purpose:      Create validated.procedures table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      37 (5 governance + 32 domain)
-- Sources:      CISIR, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.procedures (
    -- Governance columns
    validated_id                  SERIAL PRIMARY KEY,
    source_type                   TEXT NOT NULL,
    source_table                  TEXT NOT NULL,
    ingest_id                     TEXT NOT NULL,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number                TEXT,
    admission_date                TIMESTAMP,
    cisir_id                      TEXT,
    cpt_code                      TEXT,
    disposition                   TEXT,
    hospital_arrival_datetime     TIMESTAMP,
    icd9_procedure_code           TEXT,
    last_name                     TEXT,
    minutes_to_or                 NUMERIC,
    mrn                           TEXT,
    or_exit_datetime              TIMESTAMP,
    or_wheel_in_datetime          TIMESTAMP,
    order_datetime                TIMESTAMP,
    procedure_code                TEXT,
    procedure_code_type           TEXT,
    procedure_date                DATE,
    procedure_description         TEXT,
    procedure_id                  TEXT,
    procedure_provider            TEXT,
    procedure_start_datetime      TIMESTAMP,
    service_description           TEXT,
    service_id                    TEXT,
    surgery_date                  DATE,
    surgery_id                    TEXT,
    surgery_start_datetime        TIMESTAMP,
    surgery_stop_datetime         TIMESTAMP,
    time_to_or_exit_minutes       INTEGER,
    time_to_surgery_start_minutes INTEGER,
    time_to_surgery_stop_minutes  INTEGER,
    time_to_wheel_in_minutes      INTEGER,
    total_minutes_to_procedure    INTEGER,
    trauma_number                 TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_procedures_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_procedures_source_type
    ON validated.procedures (source_type);

CREATE INDEX IF NOT EXISTS idx_procedures_ingest_id
    ON validated.procedures (ingest_id);

CREATE INDEX IF NOT EXISTS idx_procedures_account_number
    ON validated.procedures (account_number);

CREATE INDEX IF NOT EXISTS idx_procedures_mrn
    ON validated.procedures (mrn);

CREATE INDEX IF NOT EXISTS idx_procedures_trauma_number
    ON validated.procedures (trauma_number);

CREATE INDEX IF NOT EXISTS idx_procedures_cisir_id
    ON validated.procedures (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.procedures IS
'Harmonized procedures data combined from: CISIR, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.procedures.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.procedures.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.procedures.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.procedures.created_at IS
'Timestamp when this row was inserted into the validated table.';

