-- =============================================================================
-- create_VALIDATED_INJURY_EVENT.sql
-- =============================================================================
-- Purpose:      Create validated.injury_event table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      19 (5 governance + 14 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.injury_event (
    -- Governance columns
    validated_id                SERIAL PRIMARY KEY,
    source_type                 TEXT NOT NULL,
    source_table                TEXT NOT NULL,
    ingest_id                   TEXT NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number              TEXT,
    icd10_external_cause_code   TEXT,
    icd9_external_cause_code    TEXT,
    injury_date                 DATE,
    injury_description_freetext TEXT,
    injury_time                 TIME,
    injury_type_description     TEXT,
    injury_type_id              TEXT,
    mechanism_of_injury         TEXT,
    mrn                         TEXT,
    place_of_injury_county      TEXT,
    place_of_injury_state       TEXT,
    place_of_injury_zipcode     TEXT,
    trauma_number               TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_injury_event_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_injury_event_source_type
    ON validated.injury_event (source_type);

CREATE INDEX IF NOT EXISTS idx_injury_event_ingest_id
    ON validated.injury_event (ingest_id);

CREATE INDEX IF NOT EXISTS idx_injury_event_account_number
    ON validated.injury_event (account_number);

CREATE INDEX IF NOT EXISTS idx_injury_event_mrn
    ON validated.injury_event (mrn);

CREATE INDEX IF NOT EXISTS idx_injury_event_trauma_number
    ON validated.injury_event (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.injury_event IS
'Harmonized injury event data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.injury_event.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.injury_event.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.injury_event.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.injury_event.created_at IS
'Timestamp when this row was inserted into the validated table.';

