-- =============================================================================
-- create_VALIDATED_PREHOSPITAL_VITALS.sql
-- =============================================================================
-- Purpose:      Create validated.prehospital_vitals table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      20 (5 governance + 15 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.prehospital_vitals (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    diastolic_bp            INTEGER,
    ems_id                  TEXT,
    gcs_eye                 INTEGER,
    gcs_motor               INTEGER,
    gcs_total               INTEGER,
    gcs_verbal              INTEGER,
    heart_rate              INTEGER,
    oxygen_saturation       INTEGER,
    respiratory_rate        INTEGER,
    systolic_bp             INTEGER,
    temperature             NUMERIC,
    trauma_number           TEXT,
    vitals_datetime         TIMESTAMP,
    vitals_location_id      TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_prehospital_vitals_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_prehospital_vitals_source_type
    ON validated.prehospital_vitals (source_type);

CREATE INDEX IF NOT EXISTS idx_prehospital_vitals_ingest_id
    ON validated.prehospital_vitals (ingest_id);

CREATE INDEX IF NOT EXISTS idx_prehospital_vitals_account_number
    ON validated.prehospital_vitals (account_number);

CREATE INDEX IF NOT EXISTS idx_prehospital_vitals_trauma_number
    ON validated.prehospital_vitals (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.prehospital_vitals IS
'Harmonized prehospital vitals data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.prehospital_vitals.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.prehospital_vitals.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.prehospital_vitals.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.prehospital_vitals.created_at IS
'Timestamp when this row was inserted into the validated table.';

