-- =============================================================================
-- create_VALIDATED_VITALS.sql
-- =============================================================================
-- Purpose:      Create validated.vitals table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      129 (5 governance + 124 domain)
-- Sources:      CISIR
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.vitals (
    -- Governance columns
    validated_id                             SERIAL PRIMARY KEY,
    source_type                              TEXT NOT NULL,
    source_table                             TEXT NOT NULL,
    ingest_id                                TEXT NOT NULL,
    created_at                               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number                           TEXT,
    admit_date                               TIMESTAMP,
    b_p_reading_at_max_diastolic_record_time TEXT,
    b_p_reading_at_max_systolic_record_time  TEXT,
    b_p_reading_at_min_diastolic_record_time TEXT,
    b_p_reading_at_min_systolic_record_time  TEXT,
    cisir_id                                 TEXT,
    gait_transfer_max                        TEXT,
    gait_transfer_max_record_time            TIMESTAMP,
    gait_transfer_min                        TEXT,
    gait_transfer_min_record_time            TIMESTAMP,
    interval_end_time                        TIMESTAMP,
    interval_start_time                      TIMESTAMP,
    max_artificial_airway                    BOOLEAN,
    max_artificial_airway_record_time        TIMESTAMP,
    max_diastolic_b_p_location               TEXT,
    max_diastolic_b_p_record_method          TEXT,
    max_diastolic_b_p_record_time            TIMESTAMP,
    max_diastolic_b_p_value                  INTEGER,
    max_fio2_percent                         INTEGER,
    max_fio2_record_time                     TIMESTAMP,
    max_gcs_eye                              INTEGER,
    max_gcs_eye_record_time                  TIMESTAMP,
    max_gcs_motor_record_time                TIMESTAMP,
    max_gcs_motor_score                      INTEGER,
    max_gcs_total                            INTEGER,
    max_gcs_total_record_time                TIMESTAMP,
    max_heartrate                            INTEGER,
    max_heartrate_record_time                TIMESTAMP,
    max_heartrate_source                     TEXT,
    max_mean_arterial_pressure               INTEGER,
    max_mean_arterial_pressure_record_time   TIMESTAMP,
    max_motor_respone_lle                    TEXT,
    max_motor_respone_lle_record_time        TIMESTAMP,
    max_motor_response_lue                   TEXT,
    max_motor_response_lue_record_time       TIMESTAMP,
    max_motor_response_rle                   TEXT,
    max_motor_response_rle_record_time       TIMESTAMP,
    max_motor_response_rue                   TEXT,
    max_motor_response_rue_record_time       TIMESTAMP,
    max_oxygen_flow_rate                     INTEGER,
    max_oxygen_flow_rate_device              TEXT,
    max_oxygen_record_time                   TIMESTAMP,
    max_patient_position                     TEXT,
    max_patient_position_record_time         TIMESTAMP,
    max_pulse                                INTEGER,
    max_pulse_record_time                    TIMESTAMP,
    max_respiratory_rate                     INTEGER,
    max_respiratory_rate_record_time         TIMESTAMP,
    max_sensation_lle                        TEXT,
    max_sensation_lle_record_time            TIMESTAMP,
    max_sensation_lue                        TEXT,
    max_sensation_lue_record_time            TIMESTAMP,
    max_sensation_rle                        TEXT,
    max_sensation_rle_record_time            TIMESTAMP,
    max_sensation_rue                        TEXT,
    max_sensation_rue_record_time            TIMESTAMP,
    max_spo2                                 INTEGER,
    max_spo2_record_time                     TIMESTAMP,
    max_systolic_b_p_location                TEXT,
    max_systolic_b_p_record_method           TEXT,
    max_systolic_b_p_record_time             TIMESTAMP,
    max_systolic_b_p_value                   INTEGER,
    max_temperature                          NUMERIC,
    max_temperature_record_time              TIMESTAMP,
    max_temperature_source                   TEXT,
    max_verbal_response                      INTEGER,
    max_verbal_response_record_time          TIMESTAMP,
    min_artificial_airway                    BOOLEAN,
    min_artificial_airway_record_time        TIMESTAMP,
    min_diastolic_b_p_location               TEXT,
    min_diastolic_b_p_record_method          TEXT,
    min_diastolic_b_p_record_time            TIMESTAMP,
    min_diastolic_b_p_value                  INTEGER,
    min_fio2_percent                         INTEGER,
    min_fio2_record_time                     TIMESTAMP,
    min_gcs_eye_record_time                  TIMESTAMP,
    min_gcs_eye_score                        INTEGER,
    min_gcs_motor_record_time                TIMESTAMP,
    min_gcs_motor_score                      INTEGER,
    min_gcs_total                            INTEGER,
    min_gcs_total_record_time                TIMESTAMP,
    min_heartrate                            INTEGER,
    min_heartrate_record_time                TIMESTAMP,
    min_heartrate_source                     TEXT,
    min_mean_arterial_pressure               INTEGER,
    min_mean_arterial_pressure_record_time   TIMESTAMP,
    min_motor_respone_lle                    TEXT,
    min_motor_respone_lle_record_time        TIMESTAMP,
    min_motor_respone_rle                    TEXT,
    min_motor_response_lue                   TEXT,
    min_motor_response_lue_record_time       TIMESTAMP,
    min_motor_response_rle_record_time       TIMESTAMP,
    min_motor_response_rue                   TEXT,
    min_motor_response_rue_record_time       TIMESTAMP,
    min_oxygen_flow_rate                     INTEGER,
    min_oxygen_flow_rate_device              TEXT,
    min_oxygen_record_time                   TIMESTAMP,
    min_patient_position                     TEXT,
    min_patient_position_record_time         TIMESTAMP,
    min_pulse                                INTEGER,
    min_pulse_record_time                    TIMESTAMP,
    min_respiratory_rate                     INTEGER,
    min_respiratory_rate_record_time         TIMESTAMP,
    min_sensation_lle                        TEXT,
    min_sensation_lle_record_time            TIMESTAMP,
    min_sensation_lue                        TEXT,
    min_sensation_lue_record_time            TIMESTAMP,
    min_sensation_rle                        TEXT,
    min_sensation_rle_record_time            TIMESTAMP,
    min_sensation_rue                        TEXT,
    min_sensation_rue_record_time            TIMESTAMP,
    min_spo2                                 INTEGER,
    min_spo2_record_time                     TIMESTAMP,
    min_systolic_b_p_location                TEXT,
    min_systolic_b_p_record_method           TEXT,
    min_systolic_b_p_record_time             TIMESTAMP,
    min_systolic_b_p_value                   INTEGER,
    min_temperature                          NUMERIC,
    min_temperature_record_time              TIMESTAMP,
    min_temperature_source                   TEXT,
    min_verbal_response                      TEXT,
    min_verbal_response_record_time          TIMESTAMP,
    trauma_number                            TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_vitals_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_vitals_source_type
    ON validated.vitals (source_type);

CREATE INDEX IF NOT EXISTS idx_vitals_ingest_id
    ON validated.vitals (ingest_id);

CREATE INDEX IF NOT EXISTS idx_vitals_account_number
    ON validated.vitals (account_number);

CREATE INDEX IF NOT EXISTS idx_vitals_trauma_number
    ON validated.vitals (trauma_number);

CREATE INDEX IF NOT EXISTS idx_vitals_cisir_id
    ON validated.vitals (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.vitals IS
'Harmonized vitals data combined from: CISIR. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.vitals.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.vitals.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.vitals.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.vitals.created_at IS
'Timestamp when this row was inserted into the validated table.';

