-- =============================================================================
-- create_VALIDATED_COMPLICATIONS.sql
-- =============================================================================
-- Purpose:      Create validated.complications table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      21 (5 governance + 16 domain)
-- Sources:      CISIR, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.complications (
    -- Governance columns
    validated_id             SERIAL PRIMARY KEY,
    source_type              TEXT NOT NULL,
    source_table             TEXT NOT NULL,
    ingest_id                TEXT NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number           TEXT,
    acs_code                 TEXT,
    admission_date           DATE,
    admission_status         TEXT,
    age                      INTEGER,
    cisir_id                 TEXT,
    complication_category    TEXT,
    complication_date        DATE,
    complication_day         INTEGER,
    complication_description TEXT,
    icd9_code                TEXT,
    icd9_complication_id     TEXT,
    last_name                TEXT,
    mrn                      TEXT,
    mrn_alt                  TEXT,
    trauma_number            TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_complications_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_complications_source_type
    ON validated.complications (source_type);

CREATE INDEX IF NOT EXISTS idx_complications_ingest_id
    ON validated.complications (ingest_id);

CREATE INDEX IF NOT EXISTS idx_complications_account_number
    ON validated.complications (account_number);

CREATE INDEX IF NOT EXISTS idx_complications_mrn
    ON validated.complications (mrn);

CREATE INDEX IF NOT EXISTS idx_complications_trauma_number
    ON validated.complications (trauma_number);

CREATE INDEX IF NOT EXISTS idx_complications_cisir_id
    ON validated.complications (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.complications IS
'Harmonized complications data combined from: CISIR, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.complications.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.complications.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.complications.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.complications.created_at IS
'Timestamp when this row was inserted into the validated table.';

