-- =============================================================================
-- create_VALIDATED_MEDICATIONS.sql
-- =============================================================================
-- Purpose:      Create validated.medications table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      39 (5 governance + 34 domain)
-- Sources:      CISIR, CLARITY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.medications (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    admin_action            TEXT,
    administration_datetime TIMESTAMP,
    admit_to_admin_minutes  INTEGER,
    admit_to_order_minutes  INTEGER,
    cisir_id                TEXT,
    dispense_as_written     BOOLEAN,
    dose                    NUMERIC,
    dose_unit               TEXT,
    dose_unit_hv            TEXT,
    encounter_csn           TEXT,
    end_datetime            DATE,
    frequency               TEXT,
    line_number             INTEGER,
    mar_action              TEXT,
    mar_admin_dept_id       TEXT,
    mar_doc_user_id         TEXT,
    medication_group        TEXT,
    medication_name         TEXT,
    medication_order_id     TEXT,
    mrn                     TEXT,
    ndc_code                TEXT,
    order_datetime          TIMESTAMP,
    order_phase_of_care     TEXT,
    pat_id                  TEXT,
    patient_location        TEXT,
    pharmacy_class          TEXT,
    pharmacy_subclass       TEXT,
    route                   TEXT,
    sig                     NUMERIC,
    smartset_group_name     TEXT,
    start_datetime          DATE,
    therapeutic_class       TEXT,
    trauma_number           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_medications_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_medications_source_type
    ON validated.medications (source_type);

CREATE INDEX IF NOT EXISTS idx_medications_ingest_id
    ON validated.medications (ingest_id);

CREATE INDEX IF NOT EXISTS idx_medications_account_number
    ON validated.medications (account_number);

CREATE INDEX IF NOT EXISTS idx_medications_mrn
    ON validated.medications (mrn);

CREATE INDEX IF NOT EXISTS idx_medications_trauma_number
    ON validated.medications (trauma_number);

CREATE INDEX IF NOT EXISTS idx_medications_cisir_id
    ON validated.medications (cisir_id);

CREATE INDEX IF NOT EXISTS idx_medications_encounter_csn
    ON validated.medications (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_medications_pat_id
    ON validated.medications (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.medications IS
'Harmonized medications data combined from: CISIR, CLARITY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.medications.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.medications.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.medications.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.medications.created_at IS
'Timestamp when this row was inserted into the validated table.';

