-- =============================================================================
-- create_VALIDATED_PREHOSPITAL_PROCEDURES.sql
-- =============================================================================
-- Purpose:      Create validated.prehospital_procedures table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      19 (5 governance + 14 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.prehospital_procedures (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    ems_id                  TEXT,
    equipment_size          TEXT,
    mrn                     TEXT,
    number_of_attempts      INTEGER,
    procedure_count         INTEGER,
    procedure_datetime      TIMESTAMP,
    procedure_description   TEXT,
    procedure_id            TEXT,
    procedure_name          TEXT,
    response                TEXT,
    success                 BOOLEAN,
    trauma_number           TEXT,
    year                    INTEGER

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_prehospital_procedures_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_prehospital_procedures_source_type
    ON validated.prehospital_procedures (source_type);

CREATE INDEX IF NOT EXISTS idx_prehospital_procedures_ingest_id
    ON validated.prehospital_procedures (ingest_id);

CREATE INDEX IF NOT EXISTS idx_prehospital_procedures_account_number
    ON validated.prehospital_procedures (account_number);

CREATE INDEX IF NOT EXISTS idx_prehospital_procedures_mrn
    ON validated.prehospital_procedures (mrn);

CREATE INDEX IF NOT EXISTS idx_prehospital_procedures_trauma_number
    ON validated.prehospital_procedures (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.prehospital_procedures IS
'Harmonized prehospital procedures data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.prehospital_procedures.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.prehospital_procedures.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.prehospital_procedures.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.prehospital_procedures.created_at IS
'Timestamp when this row was inserted into the validated table.';

