-- =============================================================================
-- create_VALIDATED_INSURANCE.sql
-- =============================================================================
-- Purpose:      Create validated.insurance table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      11 (5 governance + 6 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.insurance (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    insurance_company_name  TEXT,
    mrn                     TEXT,
    primary_insurance_id    TEXT,
    primary_insurance_name  TEXT,
    trauma_number           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_insurance_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_insurance_source_type
    ON validated.insurance (source_type);

CREATE INDEX IF NOT EXISTS idx_insurance_ingest_id
    ON validated.insurance (ingest_id);

CREATE INDEX IF NOT EXISTS idx_insurance_account_number
    ON validated.insurance (account_number);

CREATE INDEX IF NOT EXISTS idx_insurance_mrn
    ON validated.insurance (mrn);

CREATE INDEX IF NOT EXISTS idx_insurance_trauma_number
    ON validated.insurance (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.insurance IS
'Harmonized insurance data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.insurance.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.insurance.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.insurance.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.insurance.created_at IS
'Timestamp when this row was inserted into the validated table.';

