-- =============================================================================
-- create_VALIDATED_DEMOGRAPHICS.sql
-- =============================================================================
-- Purpose:      Create validated.demographics table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      34 (5 governance + 29 domain)
-- Sources:      CISIR, CLARITY, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.demographics (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    age                     INTEGER,
    cisir_id                TEXT,
    country                 TEXT,
    date_of_birth           DATE,
    encounter_csn           TEXT,
    ethnicity               TEXT,
    ethnicity_id            TEXT,
    first_name              TEXT,
    height_cm               NUMERIC,
    is_pregnant             BOOLEAN,
    language                TEXT,
    language_id             TEXT,
    last_name               TEXT,
    leaf_label              TEXT,
    marital_status          TEXT,
    marital_status_id       TEXT,
    middle_name             TEXT,
    mrn                     TEXT,
    pat_id                  TEXT,
    pediatric_age           INTEGER,
    race                    TEXT,
    race_id                 TEXT,
    sex                     TEXT,
    sex_id                  TEXT,
    state                   TEXT,
    trauma_number           TEXT,
    weight_kg               NUMERIC,
    zip_code                TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_demographics_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_demographics_source_type
    ON validated.demographics (source_type);

CREATE INDEX IF NOT EXISTS idx_demographics_ingest_id
    ON validated.demographics (ingest_id);

CREATE INDEX IF NOT EXISTS idx_demographics_account_number
    ON validated.demographics (account_number);

CREATE INDEX IF NOT EXISTS idx_demographics_mrn
    ON validated.demographics (mrn);

CREATE INDEX IF NOT EXISTS idx_demographics_trauma_number
    ON validated.demographics (trauma_number);

CREATE INDEX IF NOT EXISTS idx_demographics_cisir_id
    ON validated.demographics (cisir_id);

CREATE INDEX IF NOT EXISTS idx_demographics_encounter_csn
    ON validated.demographics (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_demographics_pat_id
    ON validated.demographics (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.demographics IS
'Harmonized demographics data combined from: CISIR, CLARITY, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.demographics.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.demographics.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.demographics.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.demographics.created_at IS
'Timestamp when this row was inserted into the validated table.';

