-- =============================================================================
-- create_VALIDATED_INJURIES.sql
-- =============================================================================
-- Purpose:      Create validated.injuries table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      18 (5 governance + 13 domain)
-- Sources:      CISIR, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.injuries (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    ais_code                TEXT,
    ais_severity            INTEGER,
    cisir_id                TEXT,
    icd10_code              TEXT,
    icd9_code               TEXT,
    injury_description      TEXT,
    iss_body_region         TEXT,
    iss_body_region_code    TEXT,
    mrn                     TEXT,
    predot_code             TEXT,
    record_id               TEXT,
    trauma_number           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_injuries_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_injuries_source_type
    ON validated.injuries (source_type);

CREATE INDEX IF NOT EXISTS idx_injuries_ingest_id
    ON validated.injuries (ingest_id);

CREATE INDEX IF NOT EXISTS idx_injuries_account_number
    ON validated.injuries (account_number);

CREATE INDEX IF NOT EXISTS idx_injuries_mrn
    ON validated.injuries (mrn);

CREATE INDEX IF NOT EXISTS idx_injuries_trauma_number
    ON validated.injuries (trauma_number);

CREATE INDEX IF NOT EXISTS idx_injuries_cisir_id
    ON validated.injuries (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.injuries IS
'Harmonized injuries data combined from: CISIR, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.injuries.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.injuries.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.injuries.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.injuries.created_at IS
'Timestamp when this row was inserted into the validated table.';

