-- =============================================================================
-- create_VALIDATED_ADMISSION.sql
-- =============================================================================
-- Purpose:      Create validated.admission table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      36 (5 governance + 31 domain)
-- Sources:      CISIR, CLARITY, TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.admission (
    -- Governance columns
    validated_id                 SERIAL PRIMARY KEY,
    source_type                  TEXT NOT NULL,
    source_table                 TEXT NOT NULL,
    ingest_id                    TEXT NOT NULL,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number               TEXT,
    admission_date               DATE,
    admission_datetime           TIMESTAMP,
    admission_status             TEXT,
    admission_time               TIME,
    admit_type                   TEXT,
    admit_type_id                TEXT,
    admit_unit                   TEXT,
    admit_unit_id                TEXT,
    cisir_id                     TEXT,
    department_name              TEXT,
    encounter_csn                TEXT,
    hospital_arrival_datetime    TIMESTAMP,
    inpatient_data_id            TEXT,
    means_of_arrival             TEXT,
    minutes_in_tru               NUMERIC,
    minutes_to_stc               NUMERIC,
    mrn                          TEXT,
    pat_id                       TEXT,
    patient_origin_id            TEXT,
    revenue_location             TEXT,
    revenue_location_id          TEXT,
    transfer_id                  TEXT,
    transfer_inst_admit_datetime TIMESTAMP,
    transfer_los                 NUMERIC,
    transfer_text                TEXT,
    transport_mode               TEXT,
    trauma_number                TEXT,
    tru_disposition_datetime     TIMESTAMP,
    tru_disposition_unit         TEXT,
    unit_flag                    TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_admission_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_admission_source_type
    ON validated.admission (source_type);

CREATE INDEX IF NOT EXISTS idx_admission_ingest_id
    ON validated.admission (ingest_id);

CREATE INDEX IF NOT EXISTS idx_admission_account_number
    ON validated.admission (account_number);

CREATE INDEX IF NOT EXISTS idx_admission_mrn
    ON validated.admission (mrn);

CREATE INDEX IF NOT EXISTS idx_admission_trauma_number
    ON validated.admission (trauma_number);

CREATE INDEX IF NOT EXISTS idx_admission_cisir_id
    ON validated.admission (cisir_id);

CREATE INDEX IF NOT EXISTS idx_admission_encounter_csn
    ON validated.admission (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_admission_pat_id
    ON validated.admission (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.admission IS
'Harmonized admission data combined from: CISIR, CLARITY, TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.admission.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.admission.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.admission.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.admission.created_at IS
'Timestamp when this row was inserted into the validated table.';

