-- =============================================================================
-- create_VALIDATED_TOXICOLOGY.sql
-- =============================================================================
-- Purpose:      Create validated.toxicology table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      23 (5 governance + 18 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.toxicology (
    -- Governance columns
    validated_id              SERIAL PRIMARY KEY,
    source_type               TEXT NOT NULL,
    source_table              TEXT NOT NULL,
    ingest_id                 TEXT NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number            TEXT,
    acetaminophen             TEXT,
    barbiturates              TEXT,
    blood_alcohol_content     NUMERIC,
    fentanyl                  TEXT,
    mrn                       TEXT,
    oxycodone                 TEXT,
    trauma_number             TEXT,
    tricyclic_antidepressants TEXT,
    uds_amphetamines          TEXT,
    uds_barbiturates          TEXT,
    uds_benzodiazepines       TEXT,
    uds_cocaine               TEXT,
    uds_marijuana             TEXT,
    uds_methadone             TEXT,
    uds_opiates               TEXT,
    uds_phencyclidine         TEXT,
    uds_salicylates           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_toxicology_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_toxicology_source_type
    ON validated.toxicology (source_type);

CREATE INDEX IF NOT EXISTS idx_toxicology_ingest_id
    ON validated.toxicology (ingest_id);

CREATE INDEX IF NOT EXISTS idx_toxicology_account_number
    ON validated.toxicology (account_number);

CREATE INDEX IF NOT EXISTS idx_toxicology_mrn
    ON validated.toxicology (mrn);

CREATE INDEX IF NOT EXISTS idx_toxicology_trauma_number
    ON validated.toxicology (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.toxicology IS
'Harmonized toxicology data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.toxicology.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.toxicology.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.toxicology.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.toxicology.created_at IS
'Timestamp when this row was inserted into the validated table.';

