-- =============================================================================
-- create_VALIDATED_DIAGNOSES.sql
-- =============================================================================
-- Purpose:      Create validated.diagnoses table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      15 (5 governance + 10 domain)
-- Sources:      CISIR
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.diagnoses (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    cisir_id                TEXT,
    diagnosis_category      TEXT,
    diagnosis_code          TEXT,
    diagnosis_code_type     TEXT,
    diagnosis_description   TEXT,
    is_primary_diagnosis    BOOLEAN,
    mrn                     TEXT,
    present_on_admission    TEXT,
    trauma_number           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_diagnoses_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_diagnoses_source_type
    ON validated.diagnoses (source_type);

CREATE INDEX IF NOT EXISTS idx_diagnoses_ingest_id
    ON validated.diagnoses (ingest_id);

CREATE INDEX IF NOT EXISTS idx_diagnoses_account_number
    ON validated.diagnoses (account_number);

CREATE INDEX IF NOT EXISTS idx_diagnoses_mrn
    ON validated.diagnoses (mrn);

CREATE INDEX IF NOT EXISTS idx_diagnoses_trauma_number
    ON validated.diagnoses (trauma_number);

CREATE INDEX IF NOT EXISTS idx_diagnoses_cisir_id
    ON validated.diagnoses (cisir_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.diagnoses IS
'Harmonized diagnoses data combined from: CISIR. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.diagnoses.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.diagnoses.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.diagnoses.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.diagnoses.created_at IS
'Timestamp when this row was inserted into the validated table.';

