-- =============================================================================
-- create_VALIDATED_PATIENT_TRACKING.sql
-- =============================================================================
-- Purpose:      Create validated.patient_tracking table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      26 (5 governance + 21 domain)
-- Sources:      CLARITY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.patient_tracking (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    bed_label               TEXT,
    department_id           TEXT,
    department_name         TEXT,
    effective_datetime      TIMESTAMP,
    encounter_csn           TEXT,
    event_datetime          TIMESTAMP,
    event_id                TEXT,
    event_sequence          TEXT,
    event_subtype           TEXT,
    event_subtype_code      TEXT,
    event_type              TEXT,
    event_type_code         TEXT,
    hospital_service        TEXT,
    level_of_care           TEXT,
    level_of_care_code      TEXT,
    patient_class           TEXT,
    patient_class_code      TEXT,
    patient_service_code    TEXT,
    room_number             TEXT,
    specialty               TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_patient_tracking_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_patient_tracking_source_type
    ON validated.patient_tracking (source_type);

CREATE INDEX IF NOT EXISTS idx_patient_tracking_ingest_id
    ON validated.patient_tracking (ingest_id);

CREATE INDEX IF NOT EXISTS idx_patient_tracking_account_number
    ON validated.patient_tracking (account_number);

CREATE INDEX IF NOT EXISTS idx_patient_tracking_encounter_csn
    ON validated.patient_tracking (encounter_csn);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.patient_tracking IS
'Harmonized patient tracking data combined from: CLARITY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.patient_tracking.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.patient_tracking.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.patient_tracking.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.patient_tracking.created_at IS
'Timestamp when this row was inserted into the validated table.';

