-- =============================================================================
-- create_VALIDATED_PREHOSPITAL_TRANSPORT.sql
-- =============================================================================
-- Purpose:      Create validated.prehospital_transport table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      14 (5 governance + 9 domain)
-- Sources:      TRAUMA_REGISTRY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.prehospital_transport (
    -- Governance columns
    validated_id                 SERIAL PRIMARY KEY,
    source_type                  TEXT NOT NULL,
    source_table                 TEXT NOT NULL,
    ingest_id                    TEXT NOT NULL,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number               TEXT,
    arrived_destination_datetime TIMESTAMP,
    arrived_patient_datetime     TIMESTAMP,
    enroute_datetime             TIMESTAMP,
    mrn                          TEXT,
    scene_arrive_datetime        TIMESTAMP,
    scene_dispatch_datetime      TIMESTAMP,
    scene_left_datetime          TIMESTAMP,
    trauma_number                TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_prehospital_transport_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_prehospital_transport_source_type
    ON validated.prehospital_transport (source_type);

CREATE INDEX IF NOT EXISTS idx_prehospital_transport_ingest_id
    ON validated.prehospital_transport (ingest_id);

CREATE INDEX IF NOT EXISTS idx_prehospital_transport_account_number
    ON validated.prehospital_transport (account_number);

CREATE INDEX IF NOT EXISTS idx_prehospital_transport_mrn
    ON validated.prehospital_transport (mrn);

CREATE INDEX IF NOT EXISTS idx_prehospital_transport_trauma_number
    ON validated.prehospital_transport (trauma_number);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.prehospital_transport IS
'Harmonized prehospital transport data combined from: TRAUMA_REGISTRY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.prehospital_transport.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.prehospital_transport.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.prehospital_transport.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.prehospital_transport.created_at IS
'Timestamp when this row was inserted into the validated table.';

