-- =============================================================================
-- create_VALIDATED_MICRO_CULTURES.sql
-- =============================================================================
-- Purpose:      Create validated.micro_cultures table for harmonized
--               cross-source data.
--
-- Schema:       validated
-- Grain:        One row per source record mapped into this domain
-- Columns:      18 (5 governance + 13 domain)
-- Sources:      CLARITY
--
-- Dependencies: validated schema must exist
--               governance.batch_log must exist (FK target for ingest_id)
--
-- Generated by: r/build_tools/generate_validated_ddls.R
-- Author:       Noel
-- Last Updated: 2026-02-04
-- =============================================================================

CREATE TABLE IF NOT EXISTS validated.micro_cultures (
    -- Governance columns
    validated_id            SERIAL PRIMARY KEY,
    source_type             TEXT NOT NULL,
    source_table            TEXT NOT NULL,
    ingest_id               TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain columns
    account_number          TEXT,
    culture_name            TEXT,
    encounter_csn           TEXT,
    order_procedure_id      TEXT,
    order_type              TEXT,
    order_value             TEXT,
    ordering_datetime       DATE,
    organism                TEXT,
    pat_id                  TEXT,
    result_datetime         DATE,
    result_line             INTEGER,
    specimen_source         TEXT,
    specimen_type           TEXT

    -- Foreign key to batch lineage
    ,CONSTRAINT fk_micro_cultures_ingest
        FOREIGN KEY (ingest_id)
        REFERENCES governance.batch_log (ingest_id)
        ON DELETE CASCADE
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_micro_cultures_source_type
    ON validated.micro_cultures (source_type);

CREATE INDEX IF NOT EXISTS idx_micro_cultures_ingest_id
    ON validated.micro_cultures (ingest_id);

CREATE INDEX IF NOT EXISTS idx_micro_cultures_account_number
    ON validated.micro_cultures (account_number);

CREATE INDEX IF NOT EXISTS idx_micro_cultures_encounter_csn
    ON validated.micro_cultures (encounter_csn);

CREATE INDEX IF NOT EXISTS idx_micro_cultures_pat_id
    ON validated.micro_cultures (pat_id);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE validated.micro_cultures IS
'Harmonized micro cultures data combined from: CLARITY. Populated by Step 6 harmonization.';

COMMENT ON COLUMN validated.micro_cultures.source_type IS
'Origin data source: CISIR, CLARITY, or TRAUMA_REGISTRY.';

COMMENT ON COLUMN validated.micro_cultures.source_table IS
'Staging table this row was sourced from.';

COMMENT ON COLUMN validated.micro_cultures.ingest_id IS
'Batch identifier linking to governance.batch_log for lineage.';

COMMENT ON COLUMN validated.micro_cultures.created_at IS
'Timestamp when this row was inserted into the validated table.';

